services:
  doction:
    image: ghcr.io/dny1020/doction:latest
    container_name: doction
    restart: unless-stopped
    env_file: .env
    volumes:
      - /mnt/ssd/doction:/data
      - /mnt/ssd/doction/logs:/logs
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
